### ISSUE TITLE
Define Review Process

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#32]
Based on feedback from the [April 1, 2022 Retro](https://github.com/HausDAO/daohaus-monorepo/wiki/Retro:-April-1,-2022) we need to define what the Review process is in the v3 [workflow](https://github.com/HausDAO/daohaus-monorepo/wiki/Process#workflow).

## Concerns

- Still unsure of what the review process is.
- Review is taking a decent amount of time.
- Defining our stages (ie Review -> Done)

We need to define what [Review](https://github.com/HausDAO/daohaus-monorepo/wiki/Process#review) is and what steps need to be completed in that phase.

How do we define review for the different types of tasks?

**Comment by jonathanprozzi** [comment]
Thanks for starting this. One thing that may be helpful is for us to collectively identify what types of Tasks we have that will need review. Also, we may want to consider splitting between Rage and Sage Review since that'll look different. What I'm thinking so far:

**Rage**
- Rage Reports (review pass before adding to Wiki)
- Rage PRs (What are our "look fors" when reviewing a Rage PR? Do we compare to the Rage Report?)
  - Do all Rage PRs still go through Code Review, but a less thorough process? For example, maybe a Rage PR review is focused on comparing to the findings in the Report more than on code quality
- Demonstrations of Learning
  - Potential review task would be if the tutorial/demonstration of learning is complete. Perhaps a link to a video or short document or code demo depending on the topic

**Sage**

- Have more thoughts here, will edit. Don't want to lose what I have already.

**Comment by earth2travis** [comment]
@jordanlesich can you please add your thoughts on a "checkpoint system"?

**Comment by earth2travis** [comment]
Part of this process should be verifying that the title is in the correct format, that the appropriate tags have been added, the issue is formatted with our templates and the PR adheres to our standards

**Comment by jonathanprozzi** [comment]
> Part of this process should be verifying that the title is in the correct format, that the appropriate tags have been added, the issue is formatted with our templates and the PR adheres to our standards

Good call! Let's update the Wiki page to include this more specifically, and then share the updated Process link.

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/wiki/Review

**Comment by earth2travis** [comment]
Should probably add a step in the review process to make sure the issue is assigned to a milestone

**Comment by earth2travis** [comment]
Should also verify if the issue has tasks (checkboxes) that all have been completed

**Comment by jonathanprozzi** [comment]
Those are all great additions @earth2travis. Let's get them added in! I'll make the basic updates if you haven't yet!

**Comment by jonathanprozzi** [comment]
Made the updates we talked about -- https://github.com/HausDAO/daohaus-monorepo/wiki/Review

Let's see if we think this can move into Done for now. We can always keep iterating @earth2travis

**Comment by earth2travis** [comment]
This looks good to me. Would be nice to have someone follow along with it next time they do a review
