### ISSUE TITLE
Component Library Folder Structure

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#43]
## What

As we're moving into Sage for the component library packages we want to align on a v1 of our folder structure. Some suggestions have been based on Atomic Design with `atoms` and `molecules` folders and a Storybook that mirrors that. Before we go too far, let's take some time to research/propose some structures.

## TODOs

- [x] Research folder structures for component libraries
- [x] Propose a folder structure for our component library / Storybook

## Deliverables

- Rage Report / HackMD with suggested folder structure for our component library
- Brief outline of next steps for putting this in place (for example, we can start integrating into both our component library and our Storybook structures)

**Comment by 0xRowdy** [comment]
Based on a few articles and past experience I would recomend sticking with an Atomic design pattern. This could allow flexability when it comes to publishing to npm. Giving users the ability to install one package that includes everything (atoms, molicules, organisims, etc) or the ability to pick and choose what they want to install on a granular basis.

> Unified design and dev language. It is much easier to collaborate with your design team now that you are using the same lingo across the board. For my devs using storybook out there, this is even more beneficial.
Scalable folder structure. We now have refined categories for our components. It is much easier to keep our UI organized even if we have 200+ components.
Minimal project context needed. Normally, a new developer needs to have a good amount of context on a project in order to find components they need. With atomic design, the language and structure are more universal, so it is much easier to say: “Well, a header is an organism, so let me check the organism folder.”
Cleaner code. How, you ask? Well, atomic design forces you to better understand the relationship between your components. Even if you start with a big, messy, multi-functional component, refactoring is a breeze when you start thinking: “OK, where do I see organisms, molecules, atoms, etc.”

https://bradfrost.com/blog/post/atomic-design-and-storybook/
https://dev.to/krisguzman_dev/a-better-way-to-structure-react-projects-96a

**Comment by jordanlesich** [comment]
This is looking great. 

What I have implemented is pretty similar, though I'll do a rework to make sure this is more exact. I'm really warming up to the idea of component folders and refactoring out things like styles, component specific types. 

In how we handle storybook, I've done some snooping on other storybook deployments in their showcase (https://storybook.js.org/showcase/) then trying to find their github repos to see how they implemented. My favourite so far is Github's React library 

https://github.com/primer/react

They use the story to separate different states and subcomponents of each atom. Then on the docs page, story book automatically lists them out. 

Story code:
https://github.com/primer/react/blob/main/src/Button/Button.stories.tsx
The Story: 
https://61a90feace7802003a4d9c45-jtvdedpfdr.chromatic.com/?path=/story/composite-components-button--default-button

Thanks Rowdy, 

The breakdown above is really helpful. I'll take time to read through those resources as well. 

Maybe @jonathanprozzi has time to file this away into the spec or wiki? Also, I'd say this is at the review stage.

**Comment by jonathanprozzi** [comment]
Closed by #55
