### ISSUE TITLE
Standardize Hub Dropdown Menus

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#536]
### Feature

Hub

### Expected outcome

All dropdowns look like the 'Filter' dropdown - same background color, same spacing, same highlighting. 

### Actual outcome

Filter, Profile, and Sort by all have different styles. (if changing 'Sort by' to dropdown styles if difficult, then leave as is).

### Browser

Chrome

### Screenshots and context

<img width="158" alt="Screen Shot 2022-07-29 at 7 52 31 AM" src="https://user-images.githubusercontent.com/42706432/181753043-81537b51-2e64-4d51-a5bb-805be6fe8a0a.png">
<img width="260" alt="Screen Shot 2022-07-29 at 7 52 35 AM" src="https://user-images.githubusercontent.com/42706432/181753045-b5efbe86-6396-47f8-9b7e-e26c57502053.png">
<img width="248" alt="Screen Shot 2022-07-29 at 7 52 40 AM" src="https://user-images.githubusercontent.com/42706432/181753046-fbb71745-970e-4687-a59b-12d5ddb5eea8.png">

**Comment by earth2travis** [comment]
We should also address this issue reported by @7helles:

**Expected Behavior**

When clicking "Settings" under "More" in the top nav, the dropdown displaying "Settings" should close automatically when the user moves to the new page, and "More" should look active/selected.

**Actual Behavior**

When clicking "Settings" under "More" in the top nav, the dropdown continues to stay open until the user clicks somewhere on the page, and "More" does not appear to be active or selected.

**Comment by jordanlesich** [comment]
Wait for hub build

**Comment by jordanlesich** [comment]
The last two, the difference is a select and a buttonDropdown. 

The first example likely won't be in the final build
