### ISSUE TITLE
Create Transaction Builder Form

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#861]

**Comment by earth2travis** [comment]
@7helles do we have the designs ready for this app?

**Comment by 7helles** [comment]
@earth2travis When Jord and I talked about this a couple weeks ago, my impression was it would probably fit in a form builder app that he has been mulling over. However, since that may get pushed out an indeterminate amount of time, there are designs that could be used as a standalone proposal form version of multicall transactions: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=7711%3A192742

**Comment by earth2travis** [comment]
@7helles do you need additional input from developers to start designs on a standalone app?

**Comment by 7helles** [comment]
@earth2travis for something that fits into a bigger form builder app, yes. We should probably have a meeting with @jordanlesich and hash out details for the project and how it fits into budget - he has a much better grasp of it than I do. If it's just going to be a proposal type accessed via the proposals modal, I think those designs could be used.

**Comment by earth2travis** [comment]
Closing as duplicate of https://github.com/HausDAO/daohaus-monorepo/issues/161
