### ISSUE TITLE
Text Breaking out of Warning on Proposal Details Error

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#884]
### Feature

Warning Toast

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Warning text should be contained within the div

### Actual Behavior

Warning text goes off the div on the right hand side

### Steps to Reproduce

1. Proposals
2. View a proposals details
3. Try to vote
4. Get error message

### Browser

Brave

### Screenshots and Context

<img width="417" alt="image" src="https://user-images.githubusercontent.com/522182/191629989-0e6e5363-fdbf-4e95-bf80-968c0fb4eb6b.png">

**Comment by jordanlesich** [comment]
The crappy thing about this is that this is how Ethers and Web3 format error messages from the contract. 

If you look closely in this massive shit-pile of gibberish, there's a small but of text that says "reason = "execution reverted: !voting""

That's more or less what we want to display, since that's the error message we get from the contract. If we can reliably get error messages from contracts, then we can start to write out real human-readable error messages and map them to the poor quality error messages in the Baal contract. 

Ticket 1: Extract real messages from this shit-pile we get back from ethers
Ticket 2: For Baal, map human readable to our bad solidity error messages (ex. instead of "reason = "execution reverted: !voting"", we can have "This proposal is not in voting period."
