### ISSUE TITLE
Change Indicator Bar to Red When Proposal is Failing Quorum

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#886]
### Feature

Proposal Card and Proposal Details

### App

- [x] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

When a proposal is failing the bar should be red

### Actual Behavior

When a proposal is failing due to quorum requirements the bar is green

### Steps to Reproduce

1. Create proposal
2. Vote on proposal 
3. View failing proposal that has not met quorum

### Browser

Brave

### Screenshots and Context

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/522182/191632677-37f95dd7-1075-4254-9fff-800f18c96230.png">

**Comment by jordanlesich** [comment]
The red in the bar is meant to represent no votes. 

If we change the color to red, then we muddle the original meaning of red. 

Perhaps the writing needs to change to represent a proposal failing because it's not meeting quorum vs. because of being voted down. Needs more design thinking before we touch the code, imo.

**Comment by earth2travis** [comment]
Gotcha. Closing out as working as intended
