### ISSUE TITLE
DAO Summon Success/Failure page needs mobile design, fix alignment issues

### ISSUE THREAD

**Issue by 7helles** [HausDAO/daohaus-monorepo#905]
### Feature

Summon Success/Failure page

### App

- [ ] [Admin](https://admin.daohaus.fun)
- [X] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Issue for mobile view of summon results screen and updates to alignment of these pages on desktop.

### Actual Behavior

Link to Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=7741%3A194899

Currently it doesn't seem like there's a responsive design for the results screens of Summon, and the alignment of elements is strange on desktop. Suggestions:

- On desktop, place content in a centered column, left-justified within the centered column
- On mobile views, allow text to break to two lines (Header, etc) if necessary, and use truncated DAO address component on Success screen
- On mobile views, change buttons to span full width

### Screenshots and Context

Current:
![current](https://user-images.githubusercontent.com/97971946/192615050-31974bc3-2a12-40bd-8745-a8bb1baab16e.png)

Suggestions:

![FireShot Capture 049 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192615097-cf0f55d0-14c2-4cc0-8755-e8632d1f9062.png)
![FireShot Capture 050 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192615119-9689e9c6-3511-486c-b5b8-39dc08d05661.png)

![FireShot Capture 051 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192615136-5de5b957-3c2c-4262-9469-ff073daf8a29.png)
![FireShot Capture 052 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192615155-ba17ef9f-c7ae-44b1-bc4a-00bd2bf29741.png)

**Comment by jordanlesich** [comment]
So I finally understand why the original design asked for the right-aligned svg. 

Turns out that if we wanted to preserve the layout, we have to preserve the layout width. 

So that svg *is* actually centerred, but just centered for the width  of the previous form. Because we can't see the size of the container, the illusion is that the SVG is aligned right when it's actually centered. 

So I got rid of the parent container width and had it center based on the actual elements, but there's a problem. Now the layout either 1) is far too wide in the form view 2) If I only apply width in form view, then transitioning between states results in the layout 'snapping'. 

I still think this is better than the seemingly awkward positioning of the SVG box that we had before. But let's keep an eye on it.
