### ISSUE TITLE
Add Visual Indicator for Shaman Proposals

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#958]
### App

- [Admin](https://admin.daohaus.fun)

### Feature Type

- Enhancement

### Feature

Add visual differential to proposal cards and proposal details views for update Shaman settings proposals. Could be a color or an icon or emoji or both. Something should notify DAO member the proposal is serious and should be considered

### Screenshots and Context

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/522182/194670780-dd82fa31-f591-45af-8b75-b2d86eb65f2e.png">

<img width="742" alt="image" src="https://user-images.githubusercontent.com/522182/194670804-9f98c089-4d35-4b61-b7ef-efdce427fe96.png">

**Comment by dekanbro** [comment]
On details page there should be a visual indicator on the action too. When people are using tx builder in the future would it be good to have a call out.

**Comment by 7helles** [comment]
I thought a good place to start would be with already-developed warning styles. Currently we use the same icon for warnings as for errors -- feel free to offer other icon suggestions if this one seems too harsh.

![Image](https://user-images.githubusercontent.com/97971946/194939599-cdd58f93-116f-43db-9f3f-d906b50bd15c.png)

- on the Overview card, could use the warning card component from the figma PL: bg orange/dark/2, border orange/dark/5, with orange/dark/11 text and a warning icon set to the left. Figma link for cards here: https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library?node-id=1355%3A259186

![Image](https://user-images.githubusercontent.com/97971946/194939628-87b8b51d-9747-4ca8-9c09-2a4411000d88.png)

- On the Proposals view, could use the warning helper text component styling from the figma PL, here: https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library?node-id=147%3A56949
- Text would be parSm instead of parXs.
