### ISSUE TITLE
Proposal Details Not Refreshing After Transactions

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#972]
### Feature

Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Would expect the proposal that was just sponsored to no longer have the sponsor button

### Actual Behavior

Sponsor Proposal button is still active after a successful [transaction](https://goerli.etherscan.io/tx/0x32684fa88b4916cd18cd2d1a3a9653e61464100767ab6899c9f9f1a9cab535e0)

[proposal](https://admin.daohaus.fun/#/molochV3/0x5/0xb2b3cf26cbd0d043d5afce7728bfc0d2fbd4b83b/proposals/12)

Goes away after refresh

### Steps to Reproduce

1. Create proposal that requires a proposal
2. Sponsor
3. View Proposal details

### Browser

Brave

### Screenshots and Context

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/522182/195418651-80b998c6-f349-4e87-9354-7f6813993eca.png">

**Comment by skuhlmann** [comment]
These probably have a lifecycle method on success to RefreshAll from the DaoContext - but the details page fetches the proposal separately. Might need to find a way to pass that down into here - but going to be a problem because these are used in proposal action on the list page as well.

- Sponsor, process and vote are the actions where this is not working on the details page only
